CREATE DATABASE GRADESDB;
USE GRADESDB;

CREATE TABLE STUDENTS (
	ID INT PRIMARY KEY,
	NAME CHAR(100),
	MARKS INT
);

INSERT INTO STUDENTS 
	(ID, NAME, MARKS) VALUES
    (1, 'Matt', 44),
    (2, 'John', 57),
    (3, 'Lucas', 78);
     
SELECT ID, NAME, MARKS,
       
    CASE
      WHEN (MARKS>90) THEN 'A+'
      WHEN (MARKS>70) THEN 'A'
      WHEN (MARKS>50) THEN 'B'
      WHEN (MARKS>=40) THEN 'C'
      ELSE 'Fail' 
    END AS GRADE
    FROM STUDENTS